//
//  GradleBuildFiles.swift
//  PSProject
//
import PathKit

enum GradleBuildFiles {
    
    // MARK: - Root project files
    
    static func writeRootBuildGradle(to dir: Path) throws {
        let content = """
        // Top-level build file - generated by PSProject
        plugins {
            id 'com.android.application' version '8.7.0' apply false
        }
        """
        try (dir + "build.gradle").write(content, encoding: .utf8)
    }
    
    static func writeSettingsGradle(to dir: Path, appName: String) throws {
        let content = """
        pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
        }
        dependencyResolution {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
                google()
                mavenCentral()
            }
        }
        
        rootProject.name = "\(appName)"
        include ':app'
        """
        try (dir + "settings.gradle").write(content, encoding: .utf8)
    }
    
    static func writeGradleProperties(to dir: Path) throws {
        let content = """
        # Project-wide Gradle settings - generated by PSProject
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        android.useAndroidX=true
        android.nonTransitiveRClass=true
        """
        try (dir + "gradle.properties").write(content, encoding: .utf8)
    }
    
    // MARK: - App module
    
    static func writeAppBuildGradle(
        to appDir: Path,
        packageName: String,
        minSdk: Int,
        targetSdk: Int,
        archs: [String]
    ) throws {
        let abiFilters = archs.map { "'\($0)'" }.joined(separator: ", ")
        
        let content = """
        plugins {
            id 'com.android.application'
        }
        
        android {
            namespace '\(packageName)'
            compileSdk \(targetSdk)
        
            defaultConfig {
                applicationId "\(packageName)"
                minSdk \(minSdk)
                targetSdk \(targetSdk)
                versionCode 1
                versionName "1.0"
        
                ndk {
                    abiFilters \(abiFilters)
                }
            }
        
            buildTypes {
                release {
                    minifyEnabled false
                }
                debug {
                    debuggable true
                }
            }
        
            sourceSets {
                main {
                    jniLibs.srcDirs = ['src/main/jniLibs']
                    assets.srcDirs = ['src/main/assets']
                }
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.7.0'
        }
        """
        try (appDir + "build.gradle").write(content, encoding: .utf8)
    }
    
    // MARK: - AndroidManifest
    
    static func writeAndroidManifest(
        to mainDir: Path,
        packageName: String,
        appName: String,
        sdlVersion: Int
    ) throws {
        let sdlActivityClass = sdlVersion == 3 ? "SDL3Activity" : "SDLActivity"
        
        let content = """
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
        
            <uses-permission android:name="android.permission.INTERNET" />
        
            <application
                android:label="\(appName)"
                android:allowBackup="true"
                android:supportsRtl="true"
                android:hardwareAccelerated="true">
        
                <activity
                    android:name=".MainActivity"
                    android:label="\(appName)"
                    android:configChanges="orientation|screenSize|keyboardHidden"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                    <meta-data
                        android:name="sdl.app.lib_name"
                        android:value="main" />
                </activity>
            </application>
        </manifest>
        """
        try (mainDir + "AndroidManifest.xml").write(content, encoding: .utf8)
    }
    
    // MARK: - Java Activity
    
    static func writeMainActivity(
        to javaDir: Path,
        packageName: String,
        sdlVersion: Int
    ) throws {
        let sdlImport: String
        let sdlParent: String
        
        if sdlVersion == 3 {
            sdlImport = "import org.libsdl.app.SDL3Activity"
            sdlParent = "SDL3Activity"
        } else {
            sdlImport = "import org.libsdl.app.SDLActivity"
            sdlParent = "SDLActivity"
        }
        
        let content = """
        package \(packageName);
        
        \(sdlImport);
        
        public class MainActivity extends \(sdlParent) {
        
            @Override
            protected String[] getLibraries() {
                return new String[] {
                    "SDL\(sdlVersion)",
                    "python3",
                    "main"
                };
            }
        }
        """
        try (javaDir + "MainActivity.java").write(content, encoding: .utf8)
    }
}
